<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report - <?php echo ucfirst($reportType); ?></title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/V/View/admin/reports/reporttemplate.css">
</head>
<body>
    <div class="report-container">
        <div class="action-bar">
            <button class="btn btn-back" onclick="window.history.back()">Back</button>
            <button class="btn" onclick="window.print()">Print / Save as PDF</button>
        </div>

        <div class="report-header">
            <div class="report-title">
                <img src="/V/View/resources/nav-logo.png" alt="Organization Logo" class="report-logo">
                <h1>V - Volunteering Platform</h1>
                <p><?php echo ucfirst($reportType); ?> Report</p>
            </div>
            <div class="report-meta">
                <p><strong>Generated At:</strong> <?php echo date('Y-m-d H:i:s'); ?></p>
                <p><strong>Generated By:</strong> <?php echo $_SESSION['name'] ?? 'Admin'; ?></p>
            </div>
        </div>

        <div class="report-info-grid">
            <div class="info-block">
                <strong>Time Range</strong>
                <span><?php echo htmlspecialchars($fromDate); ?> to <?php echo htmlspecialchars($toDate); ?></span>
            </div>
            <div class="info-block">
                <strong>Selected Metrics</strong>
                <span>
                    <?php 
                        if (!empty($options)) {
                            echo htmlspecialchars(implode(", ", array_map('ucfirst', $options)));
                        } else {
                            echo "Standard Details Only";
                        }
                    ?>
                </span>
            </div>
        </div>

        <h2>Data Overview</h2>
        
        <?php if (!empty($reportData)) : ?>
            <table class="data-table">
                <thead>
                    <tr>
                        <?php foreach (array_keys($reportData[0]) as $header): ?>
                            <th><?php echo htmlspecialchars(str_replace('_', ' ', $header)); ?></th>
                        <?php endforeach; ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($reportData as $row): ?>
                        <tr>
                            <?php foreach ($row as $cell): ?>
                                <td><?php echo htmlspecialchars((string) $cell); ?></td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <?php
            $numericColumns = [];
            $firstRow = $reportData[0];
            foreach ($firstRow as $key => $val) {
                if ($key !== 'Event_Date' && $key !== 'Join_Date' && $val != 'N/A' && is_numeric($val)) {
                    $numericColumns[] = $key;
                } elseif (is_numeric(str_replace(',','',$val))) {
                    $numericColumns[] = $key;
                }
            }

            $summaryStats = [];
            if (!empty($numericColumns)) {
                foreach ($numericColumns as $col) {
                    $values = array_column($reportData, $col);
                    $numericValues = array_map(function($v) {
                        return floatval(str_replace([',','Rs',' '], '', $v));
                    }, array_filter($values, function($v) {
                        return $v !== 'N/A' && $v !== '';
                    }));

                    if (count($numericValues) > 0) {
                        $summaryStats[$col] = [
                            'total' => array_sum($numericValues),
                            'max' => max($numericValues),
                            'min' => min($numericValues),
                            'avg' => round(array_sum($numericValues) / count($numericValues), 2)
                        ];
                    }
                }
            }
            ?>

            <?php if(!empty($summaryStats)): ?>
                <h2 style="margin-top: 40px;">Statistical Summary</h2>
                <div class="stats-grid">
                    <?php foreach($summaryStats as $column => $stats): ?>
                        <div class="stat-card">
                            <h3><?php echo htmlspecialchars(str_replace('_', ' ', $column)); ?></h3>
                            <div class="stat-line"><span>Total:</span> <strong><?php echo number_format($stats['total'], 2); ?></strong></div>
                            <div class="stat-line"><span>Average:</span> <strong><?php echo number_format($stats['avg'], 2); ?></strong></div>
                            <div class="stat-line"><span>Maximum:</span> <strong><?php echo number_format($stats['max'], 2); ?></strong></div>
                            <div class="stat-line"><span>Minimum:</span> <strong><?php echo number_format($stats['min'], 2); ?></strong></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

        <?php else : ?>
            <div class="no-data">
                No data found for the selected criteria and time range.
            </div>
        <?php endif; ?>
    </div>
</body>
</html>
